# Verbosity and settings that you pretty much just always are going to want.
alias v="nvim"
alias sv="sudo nvim"
alias g="git"
alias l="lf"
alias sl="sudo lf"
alias f="fzf"
alias bs="brew search"
alias bi="brew install"
alias mkd="mkdir -pv"
alias grep="grep --color=auto"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkd="mkdir -pv"
alias rss="newsboat"
alias cdce="cd $HOME/Code/eclipse-workspace"
alias cdcv="cd $HOME/Code/vs-code"
alias cdc="cd $HOME/Code"
alias cdcn="cd $HOME/Code/neovim"
alias cdw="cd $HOME/Documents/Work"
alias cdp="cd $HOME/Documents/Personal"
alias vz="v $HOME/.zshrc"
alias vza="v $DOTFILES/zshrc.d/20-aliases.sh"
alias vzf="v $DOTFILES/zshrc.d/50-functions.sh"
alias d="cd $DOTFILES"
alias Z="source $HOME/.zshrc"
# Show directory symbol (/) and hidden directories
alias ls='ls -p -a'
alias yt="ytfzf -c yt"
alias yta="ytfzf -m -c yt"
alias ytsa="ytfzf -m"
alias ytc="ytfzf -c yt -L"
# alias ytfd="ytfzf -L | awk '/youtube/ {print $0}' | xargs yt-dlp --add-metadata -i --write-auto-sub"
alias yts="ytfzf --pages=5"
alias ytcs="ytfzf --type=channel"
alias ytd="yt-dlp --add-metadata -i --write-auto-sub"
alias ytda="yt-dlp --add-metadata -i -x -f bestaudio/best"
alias ytfd="ytfzf -d -c yt"
alias ytfda="ytfzf -m -d -c yt"
alias whitespace="sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'"
alias s="v -c VimwikiIndex"
alias n="v $DOTFILES/neovim/.config/nvim/init.lua"
alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version"
