#!/usr/bin/env zsh

set -euo pipefail

#Append ZScaler certification to Azure CLI
#
main() {

AZCLI_PEM_FILE="/opt/homebrew/Cellar/azure-cli/$1/libexec/lib/python3.10/site-packages/certifi/cacert.pem"
ZSCALER_PEM_FILE="/Users/ragpt/Documents/ZScaler-Certificates/ZscalerRootCertificate-2048-SHA256.pem"
PATH_FILE="/Users/ragpt/.dotfiles/zshrc.d/10-path.sh"

echo "Azure PEM file location is: $AZCLI_PEM_FILE"
echo "ZScaler PEM file location is: $ZSCALER_PEM_FILE"

echo "Take backup of the Azure certificate file: cacert-backup.pem"

cp $AZCLI_PEM_FILE cacert-backup.pem

echo "Appending the content into PEM file"
cat $ZSCALER_PEM_FILE >> $AZCLI_PEM_FILE

echo "Adding the certificate into PATH"
EXPORT_TEXT="export REQUESTS_CA_BUNDLE=$AZCLI_PEM_FILE"

echo $EXPORT_TEXT >> $PATH_FILE

}

main "$@"
