#!/usr/bin/env zsh

set -euo pipefail

# Logs the user in with the account specified. Assumes CF target
# has been set already.

main() {

#  local account="${1:?No account specified}"

  # Cause script to abend if no account data stored
  pass "work/sap/btp/email" > /dev/null

  cf login \
    -a "https://api.cf.eu20.hana.ondemand.com" \
    -u "$(pass work/sap/btp/email)" \
    -p "$(pass work/sap/btp/password)"
}

main "$@"
